[profile.default]
solc-version = "0.8.1"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@forge/=lib/forge-std/src/"
]
[rpc_endpoints]
canto = "https://canto.slingshot.finance/"